<a href="https://colab.research.google.com/github/Yash-singh25/test_project/blob/master/Housing_Prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import*
from sklearn.model_selection import*
from sklearn.linear_model import *
from sklearn.preprocessing import *
from sklearn.neighbors import *
from sklearn.neural_network import *
from sklearn.ensemble import *

In [0]:
train_dataset = pd.read_csv('/content/train (1).csv')
test_dataset = pd.read_csv('/content/test (1).csv')

In [5]:
train_dataset.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [0]:
print(train_dataset.shape)
print(test_dataset.shape)

In [0]:
train_dataset.isnull().sum()

In [0]:
for i in train_dataset.keys():
  print('the total null values for {} is  {}'.format(i , train_dataset[i].isnull().sum()))

In [0]:
columns_nan_values = ['LotFrontage' , 'MasVnrArea']
columns_nan = ['MasVnrType' ,'BsmtQual' , 'BsmtCond', 'BsmtExposure', 'BsmtFinType1' , 'BsmtFinType2' , 'Electrical' , 'GarageType', 'GarageFinish' , 'GarageQual' , 'GarageCond','GarageYrBlt']

In [0]:
for i in range(len(columns_nan)):
  print('the unique value of {} is {}'.format(columns_nan[i] , train_dataset[columns_nan[i]].unique()))

In [0]:
train_dataset1 = train_dataset.copy()

In [0]:
train_dataset1 = train_dataset1.dropna(axis = 1)

In [13]:
train_dataset1.head()

   Id  MSSubClass MSZoning  LotArea  ... YrSold SaleType SaleCondition SalePrice
0   1          60       RL     8450  ...   2008       WD        Normal    208500
1   2          20       RL     9600  ...   2007       WD        Normal    181500
2   3          60       RL    11250  ...   2008       WD        Normal    223500
3   4          70       RL     9550  ...   2006       WD       Abnorml    140000
4   5          60       RL    14260  ...   2008       WD        Normal    250000

[5 rows x 62 columns]

In [30]:
train_dataset['LotFrontage'].mode()

0    60.0
dtype: float64

In [0]:
for i in train_dataset1.keys():
  print('the total null values for {} is  {}'.format(i , train_dataset1[i].isnull().sum()))

In [0]:
for i in range(len(columns_nan_values)):
  train_dataset1[columns_nan_values[i]] = train_dataset[columns_nan_values[i]].fillna(round(train_dataset[columns_nan_values[i]].mean()))

In [0]:
for i in range(len(columns_nan)):
  train_dataset1[columns_nan[i]] = train_dataset[columns_nan[i]].fillna(train_dataset[columns_nan[i]].mode()[0])

In [68]:
train_dataset1.isnull().sum()

Id              0
MSSubClass      0
MSZoning        0
LotArea         0
Street          0
               ..
GarageType      0
GarageYrBlt     0
GarageFinish    0
GarageQual      0
GarageCond      0
Length: 77, dtype: int64

In [69]:
train_dataset1.head()

   Id  MSSubClass MSZoning  ...  GarageFinish GarageQual GarageCond
0   1          60       RL  ...           RFn         TA         TA
1   2          20       RL  ...           RFn         TA         TA
2   3          60       RL  ...           RFn         TA         TA
3   4          70       RL  ...           Unf         TA         TA
4   5          60       RL  ...           RFn         TA         TA

[5 rows x 77 columns]

In [0]:
train_dataset1.pop('FireplaceQu')

In [75]:
train_dataset1.shape

(1460, 76)

In [0]:
for i in train_dataset1.keys():
  print('the unique values for {} is  {}'.format(i , train_dataset1[i].unique()))

In [0]:
train_dataset2 = train_dataset1.copy()

In [0]:
drop_columns = ['Electrical',	'GarageType','HeatingQC','SaleType',	'SaleCondition','MasVnrType','GarageFinish','Utilities',	'LotConfig',	'LandSlope'	,'RoofStyle','RoofMatl','Exterior1st','Exterior2nd','ExterCond','Foundation','Heating','Functional','BsmtQual' , 'BsmtCond', 'BsmtExposure', 'BsmtFinType1' , 'BsmtFinType2' , 'GarageQual' , 'GarageCond','GarageYrBlt','MSZoning','Neighborhood' , 'Condition1' , 'Condition2' , 'BldgType' , 'LotShape','LandContour']

In [0]:
train_dataset2 = train_dataset2.drop(train_dataset2[drop_columns],axis = 1)

In [0]:
for i in train_dataset2.keys():
  print('the length of unique values for {} is  {}'.format(i , len(train_dataset2[i].unique())))

In [107]:
train_dataset2.head()

   Id  MSSubClass  LotArea Street  ... YrSold  SalePrice  LotFrontage  MasVnrArea
0   1          60     8450   Pave  ...   2008     208500         65.0       196.0
1   2          20     9600   Pave  ...   2007     181500         80.0         0.0
2   3          60    11250   Pave  ...   2008     223500         68.0       162.0
3   4          70     9550   Pave  ...   2006     140000         60.0         0.0
4   5          60    14260   Pave  ...   2008     250000         84.0       350.0

[5 rows x 43 columns]

In [108]:
train_dataset2.shape

(1460, 43)

In [0]:
train_dataset3 = train_dataset2.copy()

In [0]:
dummy_column = ['Street'	,'HouseStyle','ExterQual','CentralAir','KitchenQual','PavedDrive']

In [0]:
train_dataset3 = train_dataset3.drop(train_dataset3[dummy_column],axis=1)

In [208]:
train_dataset3.head()

   Id  MSSubClass  LotArea  ...  SalePrice  LotFrontage  MasVnrArea
0   1          60     8450  ...     208500         65.0       196.0
1   2          20     9600  ...     181500         80.0         0.0
2   3          60    11250  ...     223500         68.0       162.0
3   4          70     9550  ...     140000         60.0         0.0
4   5          60    14260  ...     250000         84.0       350.0

[5 rows x 37 columns]

In [139]:
test_dataset.head()

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]

In [127]:
test_dataset.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [0]:
for i in test_dataset.keys():
  print('the total null values for {} is  {}'.format(i , test_dataset[i].isnull().sum()))

In [0]:
columns_nan_values_test = ['LotFrontage' , 'MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','GarageArea','TotalBsmtSF']
columns_nan_test = ['SaleType','GarageCars','Functional','KitchenQual','BsmtHalfBath','BsmtFullBath','Exterior2nd','Exterior1st','Utilities','MSZoning','MasVnrType' ,'BsmtQual' , 'BsmtCond', 'BsmtExposure', 'BsmtFinType1' , 'BsmtFinType2' , 'Electrical' , 'GarageType', 'GarageFinish' , 'GarageQual' , 'GarageCond','GarageYrBlt']

In [0]:
test_dataset1 = test_dataset.copy()

In [0]:
test_dataset1 = test_dataset1.dropna(axis = 1)

In [195]:
test_dataset1.head()

     Id  MSSubClass  LotArea Street  ... MiscVal MoSold YrSold SaleCondition
0  1461          20    11622   Pave  ...       0      6   2010        Normal
1  1462          20    14267   Pave  ...   12500      6   2010        Normal
2  1463          60    13830   Pave  ...       0      3   2010        Normal
3  1464          60     9978   Pave  ...       0      6   2010        Normal
4  1465         120     5005   Pave  ...       0      1   2010        Normal

[5 rows x 47 columns]

In [0]:
for i in range(len(columns_nan_values_test)):
  test_dataset1[columns_nan_values_test[i]] = test_dataset[columns_nan_values_test[i]].fillna(round(test_dataset[columns_nan_values_test[i]].mean()))

In [0]:
for i in range(len(columns_nan_test)):
  test_dataset1[columns_nan_test[i]] = test_dataset[columns_nan_test[i]].fillna(test_dataset[columns_nan_test[i]].mode()[0])

In [0]:
for i in test_dataset1.keys():
  print('the total null values for {} is  {}'.format(i , test_dataset1[i].isnull().sum()))

In [198]:
test_dataset1.head()

     Id  MSSubClass  LotArea  ... GarageQual GarageCond GarageYrBlt
0  1461          20    11622  ...         TA         TA      1961.0
1  1462          20    14267  ...         TA         TA      1958.0
2  1463          60    13830  ...         TA         TA      1997.0
3  1464          60     9978  ...         TA         TA      1998.0
4  1465         120     5005  ...         TA         TA      1992.0

[5 rows x 75 columns]

In [0]:
test_dataset2 = test_dataset1.copy()

In [0]:
test_dataset2 = test_dataset2.drop(test_dataset2[drop_columns],axis = 1)

In [0]:
test_dataset3 = test_dataset2.copy()

In [0]:
test_dataset3 = test_dataset3.drop(test_dataset3[dummy_column],axis=1)

In [203]:
test_dataset3.head()

     Id  MSSubClass  LotArea  ...  GarageCars  BsmtHalfBath  BsmtFullBath
0  1461          20    11622  ...         1.0           0.0           0.0
1  1462          20    14267  ...         1.0           0.0           0.0
2  1463          60    13830  ...         2.0           0.0           0.0
3  1464          60     9978  ...         2.0           0.0           0.0
4  1465         120     5005  ...         2.0           0.0           0.0

[5 rows x 36 columns]

In [211]:
print(train_dataset3.shape)
print(test_dataset3.shape)

(1460, 36)
(1459, 36)

In [0]:
y = train_dataset3.pop('SalePrice')

In [0]:
train_dataset4 = train_dataset2.copy()

In [228]:
train_dataset4.head()

   Id  MSSubClass  LotArea Street  ... YrSold  SalePrice  LotFrontage  MasVnrArea
0   1          60     8450   Pave  ...   2008     208500         65.0       196.0
1   2          20     9600   Pave  ...   2007     181500         80.0         0.0
2   3          60    11250   Pave  ...   2008     223500         68.0       162.0
3   4          70     9550   Pave  ...   2006     140000         60.0         0.0
4   5          60    14260   Pave  ...   2008     250000         84.0       350.0

[5 rows x 43 columns]

In [0]:
train_dataset5 = pd.get_dummies(train_dataset4[dummy_column])

In [230]:
train_dataset5.head()

   Street_Grvl  Street_Pave  ...  PavedDrive_P  PavedDrive_Y
0            0            1  ...             0             1
1            0            1  ...             0             1
2            0            1  ...             0             1
3            0            1  ...             0             1
4            0            1  ...             0             1

[5 rows x 23 columns]

In [0]:
train_dataset4 = train_dataset4.drop(train_dataset4[dummy_column],axis = 1)

In [0]:
for i in train_dataset5.keys():
  train_dataset4[i] = train_dataset5[i]

In [233]:
train_dataset4.head()

   Id  MSSubClass  LotArea  ...  PavedDrive_N  PavedDrive_P  PavedDrive_Y
0   1          60     8450  ...             0             0             1
1   2          20     9600  ...             0             0             1
2   3          60    11250  ...             0             0             1
3   4          70     9550  ...             0             0             1
4   5          60    14260  ...             0             0             1

[5 rows x 60 columns]

In [0]:
train_dataset4 = train_dataset4.drop(train_dataset4[['HouseStyle_2.5Fin']],axis = 1)

In [0]:
train_dataset4.pop('SalePrice')

In [248]:
train_dataset4.shape

(1460, 58)

In [0]:
test_dataset4 = test_dataset2.copy()

In [0]:
test_dataset5 = pd.get_dummies(test_dataset4[dummy_column])

In [237]:
test_dataset5.head()

   Street_Grvl  Street_Pave  ...  PavedDrive_P  PavedDrive_Y
0            0            1  ...             0             1
1            0            1  ...             0             1
2            0            1  ...             0             1
3            0            1  ...             0             1
4            0            1  ...             0             1

[5 rows x 22 columns]

In [0]:
test_dataset4 = test_dataset4.drop(test_dataset4[dummy_column],axis = 1)

In [0]:
for i in test_dataset5.keys():
  test_dataset4[i] = test_dataset5[i]

In [241]:
test_dataset4.head()

     Id  MSSubClass  LotArea  ...  PavedDrive_N  PavedDrive_P  PavedDrive_Y
0  1461          20    11622  ...             0             0             1
1  1462          20    14267  ...             0             0             1
2  1463          60    13830  ...             0             0             1
3  1464          60     9978  ...             0             0             1
4  1465         120     5005  ...             0             0             1

[5 rows x 58 columns]

In [242]:
test_dataset4.shape

(1459, 58)

In [0]:
train_dataset6 = train_dataset4.copy()
test_dataset6 = test_dataset4.copy()

In [0]:
train_dataset6 = train_dataset6.drop(train_dataset6[['Id','2ndFlrSF','WoodDeckSF','ScreenPorch','EnclosedPorch']],axis=1)
test_dataset6 = test_dataset6.drop(test_dataset6[['Id','2ndFlrSF','WoodDeckSF','ScreenPorch','EnclosedPorch']],axis = 1)

In [238]:
a = set(train_dataset5.keys())
b = set(test_dataset5.keys())
print(a-b)

{'HouseStyle_2.5Fin'}

In [0]:
obj = LassoCV()
model = obj.fit(train_dataset4,y)
predicted_train = obj.predict(train_dataset4)
predicted_test = obj.predict(test_dataset4)

In [299]:
predicted_train[0:5]

array([209479.40490318, 180079.98762207, 216727.14774718, 168756.65620187,
       281712.39948901])

In [300]:
r2_score(y , predicted_train)

0.7237416997615858